apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcp-credit-report

resources:
  - namespace.yaml
  - mcp-server/
  - api-server/
  - nextjs/

commonLabels:
  app.kubernetes.io/name: mcp-credit-report
  app.kubernetes.io/part-of: mcp-credit-report
